package projects.taskeye.web.locators;

import org.openqa.selenium.By;

public class AdminPageLocators {

    public static final By ADMIN_DETAILS_COUNTRY_DROPDOWN = By.xpath("//div[@id='country_id_chosen']");
    public static final String ADMIN_DETAILS_COUNTRY_DROPDOWN_OPTION = "//div[@id='country_id_chosen']//div[@class='chosen-drop']//ul//li[@title='%s']";
    public static final By ADMIN_DETAILS_STATE_DROPDOWN = By.xpath("//div[@id='state_id_chosen']");
    public static final String ADMIN_DETAILS_STATE_DROPDOWN_OPTION = "//div[@id='state_id_chosen']//div[@class='chosen-drop']//ul//li[@title='%s']";
    public static final By STARTUP_SCREEN_DROPDOWN = By.xpath("//div[@id='startup_screen_chosen']");
    public static final String STARTUP_SCREEN_DROPDOWN_OPTION = "//div[@id='startup_screen_chosen']//div[@class='chosen-drop']//ul//li[@title='%s']";
    public static final By TIMEZONE_DROPDOWN = By.xpath("//div[@id='chosen32_container']");
    public static final String TIMEZONE_DROPDOWN_OPTION = "//div[@id='chosen32_container']//div[@class='chosen-drop']//ul//li[@title='%s']";
    public static final By WEEK_START_DAY_DROPDOWN = By.xpath("//div[@id='week_start_day_chosen']");
    public static final String WEEK_START_DAY_DROPDOWN_OPTION = "//div[@id='week_start_day_chosen']//div[@class='chosen-drop']//ul//li[@title='%s']";
    public static By PASSWORD_FIELD = By.xpath("//input[@id='-password_value']");
    public static By TASKEYE_PROJECT = By.xpath("//div[@id='project-list']//li[@data_pid='41']");
    public static By DASHBOARD_SUB_MODULE = By.xpath("//div[@id='module-list']//ul[@data_pid='41']//li[@data_mid='41_0']//input");
    public static By TRACKING_SUB_MODULE = By.xpath("//div[@id='module-list']//ul[@data_pid='41']//li[@data_mid='41_1']//input");
    public static By CHART_SUB_MODULE = By.xpath("//div[@id='module-list']//ul[@data_pid='41']//li[@data_mid='41_3']//input");
    public static By REPORTS_SUB_MODULE = By.xpath("//div[@id='module-list']//ul[@data_pid='41']//li[@data_mid='41_2']//input");
    public static By ACTIVITY_CHILD_MODULE = By.xpath("//div[@id='sub-module-list']//ul[@data_mid='41_2']//li[@data_mid='41_s_2_0']//input");
    public static By APPROVALS_CHILD_MODULE = By.xpath("//div[@id='sub-module-list']//ul[@data_mid='41_2']//li[@data_mid='41_s_2_1']//input");
    public static By GEOFENCE_POI_CHILD_MODULE = By.xpath("//div[@id='sub-module-list']//ul[@data_mid='41_2']//li[@data_mid='41_s_2_2']//input");
    public static By ALERTS_CHILD_MODULE = By.xpath("//div[@id='sub-module-list']//ul[@data_mid='41_2']//li[@data_mid='41_s_2_3']//input");
    public static By LOGS_CHILD_MODULE = By.xpath("//div[@id='sub-module-list']//ul[@data_mid='41_2']//li[@data_mid='41_s_2_4']//input");
    public static By SETTINGS_SUB_MODULE = By.xpath("//div[@id='module-list']//ul[@data_pid='41']//li[@data_mid='41_4']//input");
    public static By GENERAL_CHILD_MODULE = By.xpath("//div[@id='sub-module-list']//ul[@data_mid='41_4']//li[@data_mid='41_s_4_0']//input");
    public static By MASTER_CHILD_MODULE = By.xpath("//div[@id='sub-module-list']//ul[@data_mid='41_4']//li[@data_mid='41_s_4_1']//input");
    public static By VIEW_PERMISSION_OF_DASHBOARD = By.xpath("//ul[@data_mid='41_0']//tr[@screenid='2390']//td[@value='1_V']");
    public static By MODIFY_PERMISSION_OF_DASHBOARD2 = By.xpath("//ul[@data_mid='41_0']//tr[@screenid='3772']//td[@value='3_A']");
    public static By VIEW_PERMISSION_OF_TRACKING = By.xpath("//ul[@data_mid='41_1']//tr[@screenid='3666']//td[@value='1_V']");
    public static By ADD_DELETE_PERMISSION_OF_TRACKING = By.xpath("//ul[@data_mid='41_1']//tr[@screenid='2176']//td[@value='3_A']");
    public static By VIEW_PERMISSION_OF_DISTANCE = By.xpath("//ul[@data_mid='41_3']//tr[@screenid='2330']//td[@value='1_V']");
    public static By VIEW_PERMISSION_OF_ALERTS = By.xpath("//ul[@data_mid='41_3']//tr[@screenid='2332']//td[@value='1_V']");
    public static By VIEW_PERMISSION_OF_ATTENDANCE_REPORT = By.xpath("//ul[@data_mid='41_s_2_0']//tr[@screenid='2146']//td[@value='1_V']");
    public static By VIEW_PERMISSION_OF_EMPLOYEE_ATTENDANCE_LOGS_REPORT = By.xpath("//ul[@data_mid='41_s_2_0']//tr[@screenid='4574']//td[@value='1_V']");
    public static By VIEW_PERMISSION_OF_EMPLOYEE_TASK_HISTORY_REPORT = By.xpath("//ul[@data_mid='41_s_2_0']//tr[@screenid='2135']//td[@value='1_V']");
    public static By VIEW_PERMISSION_OF_WORK_HOUR_REPORT = By.xpath("//ul[@data_mid='41_s_2_0']//tr[@screenid='2378']//td[@value='1_V']");
    public static By VIEW_PERMISSION_OF_EMPLOYEE_DAY_WISE_WORK_HOUR_REPORT = By.xpath("//ul[@data_mid='41_s_2_0']//tr[@screenid='3737']//td[@value='1_V']");
    public static By MODIFY_PERMISSION_OF_TASK_EYE_EMPLOYEE_DAY_WISE_DISTANCE_REPORT = By.xpath("//ul[@data_mid='41_s_2_0']//tr[@screenid='3800']//td[@value='3_A']");
    public static By VIEW_PERMISSION_OF_EMPLOYEE_PERFORMANCE_REPORT = By.xpath("//ul[@data_mid='41_s_2_0']//tr[@screenid='2346']//td[@value='1_V']");
    public static By VIEW_PERMISSION_OF_EMPLOYEE_STATUS_REPORT = By.xpath("//ul[@data_mid='41_s_2_0']//tr[@screenid='2890']//td[@value='1_V']");
    public static By MODIFY_PERMISSION_OF_EMPLOYEE_NOTES_REPORT = By.xpath("//ul[@data_mid='41_s_2_0']//tr[@screenid='4062']//td[@value='3_A']");
    public static By VIEW_PERMISSION_OF_EMPLOYEE_UNREACHABLE_EVENT_REPORT = By.xpath("//ul[@data_mid='41_s_2_0']//tr[@screenid='4292']//td[@value='1_V']");
    public static By VIEW_PERMISSION_OF_EXPENSE_REPORT = By.xpath("//ul[@data_mid='41_s_2_1']//tr[@screenid='2136']//td[@value='1_V']");
    public static By VIEW_PERMISSION_OF_REGULARIZE_REQUEST_REPORT = By.xpath("//ul[@data_mid='41_s_2_1']//tr[@screenid='4489']//td[@value='1_V']");
    public static By VIEW_PERMISSION_OF_GEOFENCE_HISTORY_REPORT = By.xpath("//ul[@data_mid='41_s_2_2']//tr[@screenid='2317']//td[@value='1_V']");
    public static By VIEW_PERMISSION_OF_POI_VISITS_REPORT = By.xpath("//ul[@data_mid='41_s_2_2']//tr[@screenid='2316']//td[@value='1_V']");
    public static By VIEW_PERMISSION_OF_EMPLOYEE_ALERT_REPORT = By.xpath("//ul[@data_mid='41_s_2_3']//tr[@screenid='2326']//td[@value='1_V']");
    public static By VIEW_PERMISSION_OF_SOS_SUMMARY_REPORT = By.xpath("//ul[@data_mid='41_s_2_3']//tr[@screenid='3538']//td[@value='1_V']");
    public static By VIEW_PERMISSION_OF_EMAIL_SUMMARY_REPORT = By.xpath("//ul[@data_mid='41_s_2_3']//tr[@screenid='1244']//td[@value='1_V']");
    public static By VIEW_PERMISSION_OF_USER_ACCESS_SUMMARY_REPORT = By.xpath("//ul[@data_mid='41_s_2_4']//tr[@screenid='1324']//td[@value='1_V']");
    public static By VIEW_PERMISSION_OF_SYSTEM_LOG_SUMMARY_REPORT = By.xpath("//ul[@data_mid='41_s_2_4']//tr[@screenid='1288']//td[@value='1_V']");
    public static By VIEW_PERMISSION_OF_TRAVEL_SUMMARY_REPORT = By.xpath("//ul[@data_mid='41_s_2_4']//tr[@screenid='1228']//td[@value='1_V']");
    public static By VIEW_PERMISSION_OF_STOPPAGE_SUMMARY_REPORT = By.xpath("//ul[@data_mid='41_s_2_4']//tr[@screenid='1217']//td[@value='1_V']");
    public static By VIEW_PERMISSION_OF_INACTIVE_SUMMARY_REPORT = By.xpath("//ul[@data_mid='41_s_2_4']//tr[@screenid='1328']//td[@value='1_V']");
    public static By MODIFY_PERMISSION_OF_ADMIN_USER = By.xpath("//ul[@data_mid='41_s_4_0']//tr[@screenid='2266']//td[@value='2_M']");
    public static By ADD_DELETE_PERMISSION_OF_RESELLER_USER = By.xpath("//ul[@data_mid='41_s_4_0']//tr[@screenid='2271']//td[@value='3_A']");
    public static By ADD_DELETE_PERMISSION_OF_COMPANY_USER = By.xpath("//ul[@data_mid='41_s_4_0']//tr[@screenid='2351']//td[@value='3_A']");
    public static By ADD_DELETE_PERMISSION_OF_COMPANY_SUB_USER = By.xpath("//ul[@data_mid='41_s_4_0']//tr[@screenid='3356']//td[@value='3_A']");
    public static By ADD_DELETE_PERMISSION_OF_EMPLOYEE = By.xpath("//ul[@data_mid='41_s_4_0']//tr[@screenid='2130']//td[@value='3_A']");
    public static By ADD_DELETE_PERMISSION_OF_ALERT = By.xpath("//ul[@data_mid='41_s_4_0']//tr[@screenid='2258']//td[@value='3_A']");
    public static By ADD_DELETE_PERMISSION_OF_ADD_TASK = By.xpath("//ul[@data_mid='41_s_4_1']//tr[@screenid='2133']//td[@value='3_A']");
    public static By ADD_DELETE_PERMISSION_OF_TASK_FORM = By.xpath("//ul[@data_mid='41_s_4_1']//tr[@screenid='2985']//td[@value='3_A']");
    public static By ADD_DELETE_PERMISSION_OF_LEAVE = By.xpath("//ul[@data_mid='41_s_4_1']//tr[@screenid='2083']//td[@value='3_A']");
    public static By ADD_DELETE_PERMISSION_OF_HOLIDAY = By.xpath("//ul[@data_mid='41_s_4_1']//tr[@screenid='2082']//td[@value='3_A']");
    public static By ADD_DELETE_PERMISSION_OF_RENAME_DEVICE_BRAND_OR_MODEL = By.xpath("//ul[@data_mid='41_s_4_1']//tr[@screenid='2221']//td[@value='3_A']");
    public static By ADD_DELETE_PERMISSION_OF_ANNOUNCEMENT_OVERVIEW = By.xpath("//ul[@data_mid='41_s_4_1']//tr[@screenid='2910']//td[@value='3_A']");
    public static By ADD_DELETE_PERMISSION_OF_CUSTOMIZE_APIS = By.xpath("//ul[@data_mid='41_s_4_1']//tr[@screenid='3322']//td[@value='3_A']");
    public static By ADD_DELETE_PERMISSION_OF_EXPENSE = By.xpath("//ul[@data_mid='41_s_4_1']//tr[@screenid='4024']//td[@value='3_A']");
    public static By ADD_DELETE_PERMISSION_OF_EASY_REMOVE = By.xpath("//ul[@data_mid='41_s_4_1']//tr[@screenid='3659']//td[@value='3_A']");
    public static By SERVER_IP_FIELD = By.xpath("//input[@id='-server_ip']");
    public static By SOS_AUTHORIZED_IP_FIELD = By.xpath("//input[@id='-sos_authorised_ip_d']");
    public static By DOMAIN_FIELD = By.xpath("//input[@id='-domain_name']");
    public static By ANDROID_APP_LINK_FIELD = By.xpath("//textarea[@id='-android_app_link']");
    public static By IOS_APP_LINK_FIELD = By.xpath("//textarea[@id='-ios_app_link']");
    public static By SEARCH_FIELD = By.xpath("//input[@name='searchterm']");
    public static By EDIT_RULE_BUTTON = By.xpath("//img[@id='editImageDarkMode']");
    public static By DELETE_SUB_ADMIN_USER_BUTTON = By.xpath("//img[@id='deleteFrameIcon']");
    public static By NO_ACCESS_PERMISSION_OF_DASHBOARD = By.xpath("//ul[@data_mid='41_0']//tr[@screenid='2390']//td[@value='0_N']");
    public static By USERNAME_FIELD_SUB_ADMIN_USER = By.xpath("//input[@id='-username_i']");
    public static By CONFIRM_USERNAME_FIELD_SUB_ADMIN_USER = By.xpath("//input[@id='-confirm_username']");
    public static By PASSWORD_FIELD_SUB_ADMIN_USER = By.xpath("//input[@id='-password_i']");
    public static By RETYPE_PASSWORD_FIELD_SUB_ADMIN_USER = By.xpath("//input[@id='-retype_password_i']");
    public static By MOBILE_NUMBER_FIELD_SUB_ADMIN_USER = By.xpath("//input[@id='-mob_no_i']");
    public static By PASSWORD_RECOVERY_EMAIL_FIELD_SUB_ADMIN_USER = By.xpath("//input[@id='-password_recovery_email']");
}
